server:
  port: 9094


spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/order_ms_db
      host: localhost
      port: 27017
      database: order_ms_db


#Command for connecting to mongoDB 
# Step: 1 open terminal and hit below command then open the MongoDB compass 
#     sudo mongod --dbpath=/Users/umakantpatel/data/db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: false
